
const $=id=>document.getElementById(id);let current=null,currentPath='',busy=false,jobStarted=0,timer=null;
async function api(url,options){const response=await fetch(url,options);const data=await response.json();if(!response.ok)throw Error(data.error||'Request failed');return data;}
const format=v=>v==null?'—':Number(v).toFixed(5), sci=v=>v==null?'—':Number(v).toExponential(2), percentage=v=>`${Math.round(100*v)}%`;
const heatColors=[[247,251,255],[198,219,239],[107,174,214],[49,130,189],[8,48,107]];
function heatColor(t){const u=Math.max(0,Math.min(1,t))*4,i=Math.min(3,Math.floor(u)),f=u-i;return heatColors[i].map((v,k)=>Math.round(v+(heatColors[i+1][k]-v)*f));}
function heatLayer(h,el,frame,defs,point,ox,oy,width,height){
 const n=h.resolution,[low,high]=h.transformed_range,span=high-low;
 if(!h.image){const canvas=document.createElement('canvas');canvas.width=n;canvas.height=n;const context=canvas.getContext('2d'),pixels=context.createImageData(n,n);for(let row=0;row<n;row++)for(let col=0;col<n;col++){const value=Math.asinh(h.values[n-1-row][col]/h.scale),rgb=heatColor((value-low)/span),i=(row*n+col)*4;pixels.data.set([...rgb,255],i);}context.putImageData(pixels,0,0);h.image=canvas.toDataURL();}
 el('image',{href:h.image,x:ox,y:oy,width,height,preserveAspectRatio:'none'},frame);
 // Marching squares on the evaluated Lyapunov function; contours use actual V.
 const [lo,hi]=h.bounds;for(let k=1;k<8;k++){const level=h.scale*Math.sinh(low+span*k/8);let d='';for(let y=0;y<n-1;y++)for(let x=0;x<n-1;x++){const corners=[[x,y],[x+1,y],[x+1,y+1],[x,y+1]],crossings=[];for(let a=0;a<4;a++){const b=(a+1)%4,[ax,ay]=corners[a],[bx,by]=corners[b],va=h.values[ay][ax],vb=h.values[by][bx];if((va<level)!==(vb<level)){const f=(level-va)/(vb-va);crossings.push(point([lo[0]+(ax+f*(bx-ax))/(n-1)*(hi[0]-lo[0]),lo[1]+(ay+f*(by-ay))/(n-1)*(hi[1]-lo[1])]));}}for(let j=0;j+1<crossings.length;j+=2)d+=`M${crossings[j].join(',')}L${crossings[j+1].join(',')}`;}el('path',{d,fill:'none',stroke:'#284e72','stroke-width':.7,opacity:.26},frame);}
 const grad=el('linearGradient',{id:'heatScale'},defs);heatColors.forEach((rgb,i)=>el('stop',{offset:i/4,'stop-color':`rgb(${rgb})`},grad));const barWidth=Math.min(width,340),left=450-barWidth/2,top=610;
 el('rect',{x:left,y:top,width:barWidth,height:10,fill:'url(#heatScale)',stroke:'#9db3c9','stroke-width':.5});h.ticks.forEach((v,i)=>{const x=left+barWidth*i/4;el('line',{x1:x,x2:x,y1:top+10,y2:top+14,stroke:'#71899f'});el('text',{x,y:top+28,fill:'#59738c','font-size':11,'text-anchor':'middle'}).textContent=Math.abs(v)<1e-12?'0':Math.abs(v)<.01||Math.abs(v)>=1000?v.toExponential(1):Number(v.toPrecision(3)).toString();});el('text',{x:450,y:top+49,fill:'#59738c','font-size':12,'text-anchor':'middle'}).textContent='V(x) · asinh colour scale';
}
function draw(){if(!current)return;const svg=$('plot');svg.replaceChildren();$('empty').style.display='none';const NS='http://www.w3.org/2000/svg';
function el(tag,attributes,parent=svg){const e=document.createElementNS(NS,tag);Object.entries(attributes).forEach(([k,v])=>e.setAttribute(k,v));parent.appendChild(e);return e;}
const [lo,hi]=current.view_bounds||current.protocol.plot_bounds;const scale=Math.min(790/(hi[0]-lo[0]),510/(hi[1]-lo[1]));const width=(hi[0]-lo[0])*scale,height=(hi[1]-lo[1])*scale,ox=(900-width)/2,oy=20;
const point=p=>[ox+(p[0]-lo[0])*scale,oy+height-(p[1]-lo[1])*scale];
const defs=el('defs',{});const clip=el('clipPath',{id:'clip'},defs);el('rect',{x:ox,y:oy,width,height},clip);const frame=el('g',{'clip-path':'url(#clip)'});
if($('showHeatmap').checked&&current.lyapunov)heatLayer(current.lyapunov,el,frame,defs,point,ox,oy,width,height);
for(let i=0;i<=5;i++){let x=ox+width*i/5,y=oy+height*i/5;el('line',{x1:x,y1:oy,x2:x,y2:oy+height,stroke:'#edf1f3'},frame);el('line',{x1:ox,y1:y,x2:ox+width,y2:y,stroke:'#edf1f3'},frame);let tx=el('text',{x,y:oy+height+24,'text-anchor':'middle',fill:'#7a8a94','font-size':11});tx.textContent=(lo[0]+(hi[0]-lo[0])*i/5).toFixed(2);let ty=el('text',{x:ox-10,y:y+4,'text-anchor':'end',fill:'#7a8a94','font-size':11});ty.textContent=(hi[1]-(hi[1]-lo[1])*i/5).toFixed(2);}
if($('showField').checked){current.field.points.forEach((p,i)=>{const v=current.field.velocities[i],n=Math.hypot(...v);if(!Number.isFinite(n)||n<1e-12)return;const [x,y]=point(p),dx=7*v[0]/n,dy=-7*v[1]/n;el('path',{d:`M ${x-dx/2} ${y-dy/2} L ${x+dx/2} ${y+dy/2} m ${-dx*.4-dy*.25} ${-dy*.4+dx*.25} L ${x+dx/2} ${y+dy/2} l ${-dx*.4+dy*.25} ${-dy*.4-dx*.25}`,fill:'none',stroke:'#b4c1ca','stroke-width':.85,opacity:.8},frame);});}
function path(points,attributes){return el('polyline',{points:points.map(p=>point(p).join(',')).join(' '),fill:'none',...attributes},frame);}
current.rollouts.forEach(r=>{const ood=r.group==='ood_ring'||r.group==='ood_trajectory',along=r.group==='along_trajectory';if(!$(ood?'showOOD':along?'showAlong':'showID').checked)return;const color=ood?'#9a4774':along?'#596b91':'#28766b';path(r.path,{stroke:color,'stroke-width':1.15,opacity:.65,'stroke-dasharray':ood?'5 3':along?'2 3':''});const [x,y]=point(r.position);el(ood?'polygon':'circle',ood?{points:`${x},${y-3.3} ${x-3.3},${y+2.8} ${x+3.3},${y+2.8}`,fill:color}:{cx:x,cy:y,r:2.4,fill:color},frame);});
if($('showDemos').checked)current.demonstrations.forEach((d,i)=>path(d,{stroke:'#233642','stroke-width':1.7,opacity:current.metrics.training_demo_ids.includes(i)?.9:.5,'stroke-dasharray':current.metrics.training_demo_ids.includes(i)?'':'6 4'}));
const [tx,ty]=point([0,0]);el('circle',{cx:tx,cy:ty,r:5,fill:'#142d38',stroke:'white','stroke-width':2});let label=el('text',{x:tx+9,y:ty-8,fill:'#142d38','font-size':11});label.textContent='target';
let xlabel=el('text',{x:450,y:oy+height+46,fill:'#617681','font-size':12,'text-anchor':'middle'});xlabel.textContent='Normalized x';}
const isNeural=c=>c.method==='snds';
const modelLabel=c=>isNeural(c)?'SNDS':`PLYDS · P${c.policy_degree}/V${c.lyapunov_degree}`;
function show(data,path){current=data;currentPath=path;const c=data.config,m=data.metrics,g=data.groups;$('plotTitle').textContent=`${c.motion.replaceAll('_',' ')} · vector field & rollouts`;$('plotSubtitle').textContent=isNeural(c)?`SNDS · CPU · ${c.epochs} epochs · ${c.n_demos} training demonstrations`:`Policy degree ${c.policy_degree} · Lyapunov degree ${c.lyapunov_degree} (${c.learn_lyapunov?'learned':'fixed'}) · ${c.n_demos} training demonstrations`;
const version=data.protocol.version,legacy=!['lasa-rollouts-v3','lasa-rollouts-v4'].includes(version),ood=g.ood_all||g.ood_ring;$('showAlong').parentElement.hidden=!legacy;
$('idCount').textContent=`${g.id_all.count} ${legacy?'archived ID starts':'trajectory starts · 1–2% offsets'}`;
$('oodCount').textContent=version==='lasa-rollouts-v4'?`${g.ood_ring.count} ring + ${g.ood_trajectory.count} trajectory starts`:`${ood.count} archived OOD starts`;
$('protocolNote').textContent=version==='lasa-rollouts-v4'?`v4 evaluation · ID: 1–2% offsets · OOD: ring ${g.ood_ring.target_count}/${g.ood_ring.count}, along trajectories ${g.ood_trajectory.target_count}/${g.ood_trajectory.count} reached target (5–6.25% offsets)`:`Archived ${version.split('-').at(-1)} evaluation: original starting points retained.`;
$('method').value=isNeural(c)?'snds':'plyds';for(const [id,key] of [['epochs','epochs'],['seed','seed'],['decay','decay_rate'],['margin','quadratic_margin'],['learningRate','learning_rate'],['motion','motion'],['policy','policy_degree'],['lyapunov','lyapunov_degree'],['demos','n_demos'],['selection','demo_selection'],['steps','alternating_steps'],['samples','samples_per_demo']])if(c[key]!=null)$(id).value=c[key];$('learn').checked=c.learn_lyapunov;optionsChanged();
$('mse').textContent=format(m.heldout_velocity_mse);$('heldoutCount').textContent=`${m.heldout_demo_ids.length} held-out demonstrations`;$('idRate').textContent=percentage(g.id_all.target_rate);$('oodRate').textContent=percentage(ood.target_rate);$('elapsed').textContent=m.elapsed_seconds.toFixed(2)+' s';$('totalTime').textContent=(data.source_run?'Re-evaluation ':'Full run ')+data.total_elapsed_seconds.toFixed(1)+' s';$('residualLabel').textContent=isNeural(c)?'Maximum sampled decay residual':'Coefficient residual';$('eigenvalueLabel').textContent=isNeural(c)?'Minimum V − margin · ‖x‖²':'Minimum derivative Gram eigenvalue';$('residual').textContent=sci(isNeural(c)?m.maximum_decay_residual:m.coefficient_residual);$('eigenvalue').textContent=sci(isNeural(c)?m.minimum_lower_bound_slack:m.r_min_eigenvalue);$('origin').textContent=sci(m.origin_velocity_norm);$('solverStatus').textContent=m.status.replaceAll('_',' ');$('solverStatus').className='badge'+(!['optimal','trained'].includes(m.status)||m.warnings.length?' warn':'');$('warnings').textContent=(m.warnings.length?m.warnings.join(' ')+' ':'')+(isNeural(c)?`${m.audit_points} sampled points; ${m.decay_violations} decay and ${m.lower_bound_violations} lower-bound violations (tolerance ${m.audit_tolerance}). `:'')+'Numerical checks and finite rollouts do not constitute a rigorous global stability certificate.';
$('heatmapNote').textContent=`Colour shows the ${data.lyapunov.source}. Contours mark equal values; negative numerical values are preserved.`;$('runLocation').textContent=path;$('downloads').replaceChildren();for(const [label,file] of [['Figure PNG','vector-field.png'],['Figure PDF','vector-field.pdf'],[isNeural(c)?'Model PT':'Model NPZ',isNeural(c)?'model.pt':'model.npz'],['Results JSON','result.json'],['Full rollouts','rollouts.npz'],['Protocol','protocol.json'],...(isNeural(c)?[['Lyapunov audit','audit.npz'],['Fit samples','training-data.npz']]:[])]){const a=document.createElement('a');a.className='link';a.textContent=label;a.href='/files/'+path+'/'+file;a.target='_blank';$('downloads').appendChild(a);}draw();}
async function loadRun(path){show(await api('/api/run?path='+encodeURIComponent(path)),path);$('history').value=path;window.history.replaceState(null,'','?run='+encodeURIComponent(path));if(!busy)$('status').className='statusbox';}
async function refresh(loadDefault=false){const runs=await api('/api/runs');$('history').replaceChildren(new Option('Choose a saved run…',''));for(const r of runs)$('history').add(new Option(`${r.config.motion} · ${modelLabel(r.config)} · ${r.config.n_demos} demos${r.config.demo_selection==='cover_starts'?' · covered starts':''} · ${r.protocol_version.split('-').at(-1)}`,r.path));if(currentPath)$('history').value=currentPath;if(loadDefault&&runs.length){const chosen=runs.find(r=>r.protocol_version==='lasa-rollouts-v4')||runs[0];await loadRun(chosen.path);}const galleries=await api('/api/galleries');$('gallerySelect').replaceChildren();for(const g of galleries){const prefix=g.path.slice(0,g.path.lastIndexOf('/')+1),members=runs.filter(r=>r.path.startsWith(prefix)),methods=[...new Set(members.map(r=>(r.config.method||'plyds').toUpperCase()))].join(' / '),versions=[...new Set(members.map(r=>r.protocol_version.split('-').at(-1)))].join(' / '),motions=new Set(members.map(r=>r.config.motion)).size;const name=g.name.includes('covered')?'Multimodal: branches covered':g.name.includes('complexity')?'Multimodal: unseen branch':motions?`${motions} LASA motions`:'Archived grid';$('gallerySelect').add(new Option([methods,name,versions].filter(Boolean).join(' · '),g.path));}if(galleries.length)$('galleryImage').src='/files/'+galleries[0].path;}
function optionsChanged(){const neural=$('method').value==='snds';$('polynomialOptions').hidden=neural;$('alternatingOptions').hidden=neural;$('neuralOptions').hidden=!neural;$('backend').textContent=neural?'SNDS / CPU':'SCS / CPU';$('neuralOptions').querySelectorAll('input').forEach(input=>input.disabled=!neural);if(Number($('lyapunov').value)>2){$('learn').checked=true;$('learn').disabled=true;}else $('learn').disabled=false;$('lyapunovHint').textContent=$('learn').checked?'Alternating SOS search: fit the policy and adapt its Lyapunov function in separate steps.':'Fixed quadratic V = x² + y². Higher degrees use an alternating SOS search.';const n=7-Number($('demos').value);$('splitHint').textContent=n?`The remaining ${n} demonstration${n===1?' is':'s are'} held out.`:'All demonstrations used for training; held-out error will be unavailable.';}
['method','lyapunov','demos','learn'].forEach(id=>$(id).addEventListener('change',optionsChanged));['showField','showDemos','showID','showOOD','showAlong','showHeatmap'].forEach(id=>$(id).addEventListener('change',draw));
$('method').addEventListener('change',()=>{$('selection').value=$('method').value==='snds'?'cover_starts':'first';if($('method').value==='snds')$('epochs').value=$('epochs').defaultValue;});
$('history').addEventListener('change',()=>{$('history').value&&loadRun($('history').value).catch(showError)});$('refresh').onclick=()=>refresh().catch(showError);
function showError(error){$('status').className='statusbox visible error';$('status').textContent=error.message;}
$('trainForm').onsubmit=async event=>{event.preventDefault();if(busy)return;busy=true;$('trainButton').disabled=true;jobStarted=performance.now();let stage='Starting';timer=setInterval(()=>{$('status').textContent=`${stage} · ${((performance.now()-jobStarted)/1000).toFixed(1)} s elapsed`;},200);$('status').className='statusbox visible';
try{const request={method:$('method').value,motion:$('motion').value,n_demos:Number($('demos').value),samples_per_demo:Number($('samples').value),demo_selection:$('selection').value};Object.assign(request,request.method==='snds'?{epochs:Number($('epochs').value),seed:Number($('seed').value),decay_rate:Number($('decay').value),quadratic_margin:Number($('margin').value),learning_rate:Number($('learningRate').value)}:{policy_degree:Number($('policy').value),lyapunov_degree:Number($('lyapunov').value),learn_lyapunov:$('learn').checked,alternating_steps:Number($('steps').value)});const job=await api('/api/train',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(request)});
while(true){await new Promise(resolve=>setTimeout(resolve,700));const state=await api('/api/jobs/'+job.id);stage=state.message;if(state.state==='failed')throw Error(state.message);if(state.state==='complete'){clearInterval(timer);await refresh();await loadRun(state.result);$('status').textContent=`Saved. ${current.groups.all.count} evaluation rollouts completed.`;break;}}
}catch(error){clearInterval(timer);showError(error);}finally{busy=false;$('trainButton').disabled=false;}};
$('galleryButton').onclick=()=>{$('gallery').hidden=false;$('gallery').scrollIntoView({behavior:'smooth'});};$('gallerySelect').onchange=()=>{$('galleryImage').src='/files/'+$('gallerySelect').value;};
(async()=>{try{const data=await api('/api/motions');for(const motion of data.motions)$('motion').add(new Option(motion.replaceAll('_',' '),motion));$('motion').value='Sine';optionsChanged();const saved=new URLSearchParams(location.search).get('run');await refresh(!saved);if(saved)await loadRun(saved);$('epochs').value=$('epochs').defaultValue;}catch(error){showError(error);}})();
